# TCL File Generated by Component Editor 18.1
# Sun Mar 21 18:27:51 MSK 2021
# DO NOT MODIFY


#
# test "test" v1.0
#  2021.03.21.18:27:51
#
#

#
# request TCL package from ACDS 16.1
#
package require -exact qsys 16.1


#
# module test
#
set_module_property DESCRIPTION ""
set_module_property NAME test
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME test
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


#
# file sets
#
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL test
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
ad_fileset_file test.sv SYSTEM_VERILOG PATH test.sv TOP_LEVEL_FILE
add_fileset_file test2.sv SYSTEM_VERILOG PATH test.sv
add_fileset_file test3.sv SYSTEM_VERILOG PATH test.sv
add_fileset_file test4.sv SYSTEM_VERILOG PATH test.sv
add_fileset_file test5.sv SYSTEM_VERILOG PATH test.sv
add_fileset_file test6.sv SYSTEM_VERILOG PATH test.sv



#
# parameters
#
add_parameter DATAWIDTH INTEGER 32
set_parameter_property DATAWIDTH DEFAULT_VALUE 32
set_parameter_property DATAWIDTH DISPLAY_NAME DATAWIDTH
set_parameter_property DATAWIDTH TYPE INTEGER
set_parameter_property DATAWIDTH UNITS None
set_parameter_property DATAWIDTH HDL_PARAMETER true
add_parameter ADDRESSWIDTH INTEGER 32
set_parameter_property ADDRESSWIDTH DEFAULT_VALUE 32
set_parameter_property ADDRESSWIDTH DISPLAY_NAME ADDRESSWIDTH
set_parameter_property ADDRESSWIDTH TYPE INTEGER
set_parameter_property ADDRESSWIDTH UNITS None
set_parameter_property ADDRESSWIDTH HDL_PARAMETER true


#
# display items
#


#
# connection point clock
#
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


#
# connection point avms
#
add_interface avms avalon end
set_interface_property avms addressUnits WORDS
set_interface_property avms associatedClock clock
set_interface_property avms associatedReset reset_sink
set_interface_property avms bitsPerSymbol 8
set_interface_property avms burstOnBurstBoundariesOnly false
set_interface_property avms burstcountUnits WORDS
set_interface_property avms explicitAddressSpan 0
set_interface_property avms holdTime 0
set_interface_property avms linewrapBursts false
set_interface_property avms maximumPendingReadTransactions 0
set_interface_property avms maximumPendingWriteTransactions 0
set_interface_property avms readLatency 0
set_interface_property avms readWaitTime 1
set_interface_property avms setupTime 0
set_interface_property avms timingUnits Cycles
set_interface_property avms writeWaitTime 0
set_interface_property avms ENABLED true
set_interface_property avms EXPORT_OF ""
set_interface_property avms PORT_NAME_MAP ""
set_interface_property avms CMSIS_SVD_VARIABLES ""
set_interface_property avms SVD_ADDRESS_GROUP ""

add_interface_port avms avms_address address Input ADDRESSWIDTH
add_interface_port avms avms_read read Input 1
add_interface_port avms avms_write write Input 1
add_interface_port avms avms_writedata writedata Input DATAWIDTH
add_interface_port avms avms_byteenable byteenable Input DATAWIDTH/8
add_interface_port avms avms_readdata readdata Output DATAWIDTH
set_interface_assignment avms embeddedsw.configuration.isFlash 0
set_interface_assignment avms embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avms embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avms embeddedsw.configuration.isPrintableDevice 0


#
# connection point reset_sink
#
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink rst_n reset_n Input 1
