# TCL File Generated by i don't choose now
Fri Apr 16 21:08:48 2021
DO NOT MODIFY


#
# test test v1.0
# Fri Apr 16 21:08:48 2021
#
#

#
# request TCL package from ACDS 16.1
#
package require -exact qsys 16.1


#
# module test
#
set_module_property DESCRIPTION ""
set_module_property NAME test
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME test
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


#
#file sets
#
