# TCL File Generated by i don't choose now
Tue Apr 20 14:15:11 2021
DO NOT MODIFY


#
# test test v1.0
# Tue Apr 20 14:15:11 2021
#
#

#
# request TCL package from ACDS 16.1
#
package require -exact qsys 16.1


#
# module test
#
set_module_property DESCRIPTION ""
set_module_property NAME test
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME test
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


#
#file sets
#
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" "" 
set_fileset_property QUARTUS_SYNTH TOP_LEVEL test
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file test.sv SYSTEM_VERILOG PATH test.sv TOP_LEVEL_FILE
add_fileset_file test2.sv SYSTEM_VERILOG PATH test.sv
add_fileset_file test3.sv SYSTEM_VERILOG PATH test.sv
add_fileset_file test4.sv SYSTEM_VERILOG PATH test.sv
add_fileset_file test5.sv SYSTEM_VERILOG PATH test.sv
add_fileset_file test6.sv SYSTEM_VERILOG PATH test.sv


#
#paramaters
#
add_parameter DATAWIDTH INTEGER 32
set_parameter_property DATAWIDTH DEFAULT_VALUE 32
set_parameter_property DATAWIDTH DISPLAY_NAME DATAWIDTH
set_parameter_property DATAWIDTH TYPE INTEGER
set_parameter_property DATAWIDTH UNITS None
set_parameter_property DATAWIDTH HDL_PARAMETER true
add_parameter ADDRESSWIDTH INTEGER 32
set_parameter_property ADDRESSWIDTH DEFAULT_VALUE 32
set_parameter_property ADDRESSWIDTH DISPLAY_NAME ADDRESSWIDTH
set_parameter_property ADDRESSWIDTH TYPE INTEGER
set_parameter_property ADDRESSWIDTH UNITS None
set_parameter_property ADDRESSWIDTH HDL_PARAMETER true
